"""Initial migration

Revision ID: d089e33667f2
Revises: 
Create Date: 2025-03-25 20:22:31.221581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd089e33667f2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('metric_type', sa.String(length=50), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('dimensions', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_metrics_metric_type'), 'app_metrics', ['metric_type'], unique=False)
    op.create_index(op.f('ix_app_metrics_timestamp'), 'app_metrics', ['timestamp'], unique=False)
    op.create_index('ix_app_metrics_timestamp_type', 'app_metrics', ['timestamp', 'metric_type'], unique=False)
    op.create_table('bookmakers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.Column('update_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookmakers_external_id'), 'bookmakers', ['external_id'], unique=True)
    op.create_index('ix_bookmakers_is_active_priority', 'bookmakers', ['is_active', 'priority'], unique=False)
    op.create_index(op.f('ix_bookmakers_name'), 'bookmakers', ['name'], unique=False)
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('flag_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.Column('update_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_countries_code'), 'countries', ['code'], unique=False)
    op.create_index(op.f('ix_countries_external_id'), 'countries', ['external_id'], unique=False)
    op.create_index(op.f('ix_countries_name'), 'countries', ['name'], unique=True)
    op.create_table('fixture_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_code', sa.String(length=10), nullable=True),
    sa.Column('long_description', sa.String(length=100), nullable=True),
    sa.Column('status_type', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_code')
    )
    op.create_index('ix_fixture_statuses_short_code_type', 'fixture_statuses', ['short_code', 'status_type'], unique=False)
    op.create_index(op.f('ix_fixture_statuses_status_type'), 'fixture_statuses', ['status_type'], unique=False)
    op.create_table('media_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.Column('update_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_assets_type'), 'media_assets', ['type'], unique=False)
    op.create_table('odds_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('key', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.Column('update_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_odds_types_category'), 'odds_types', ['category'], unique=False)
    op.create_index('ix_odds_types_category_order', 'odds_types', ['category', 'display_order'], unique=False)
    op.create_index(op.f('ix_odds_types_external_id'), 'odds_types', ['external_id'], unique=True)
    op.create_index(op.f('ix_odds_types_key'), 'odds_types', ['key'], unique=False)
    op.create_table('performance_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('component', sa.String(length=100), nullable=True),
    sa.Column('operation', sa.String(length=100), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('trace_id', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_logs_component'), 'performance_logs', ['component'], unique=False)
    op.create_index('ix_performance_logs_component_operation', 'performance_logs', ['component', 'operation'], unique=False)
    op.create_index(op.f('ix_performance_logs_operation'), 'performance_logs', ['operation'], unique=False)
    op.create_index(op.f('ix_performance_logs_status'), 'performance_logs', ['status'], unique=False)
    op.create_index(op.f('ix_performance_logs_timestamp'), 'performance_logs', ['timestamp'], unique=False)
    op.create_index('ix_performance_logs_timestamp_status', 'performance_logs', ['timestamp', 'status'], unique=False)
    op.create_index(op.f('ix_performance_logs_trace_id'), 'performance_logs', ['trace_id'], unique=False)
    op.create_table('update_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=True),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('update_type', sa.String(length=20), nullable=True),
    sa.Column('update_by', sa.String(length=50), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('old_data', sa.JSON(), nullable=True),
    sa.Column('new_data', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_success', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_update_logs_record_id'), 'update_logs', ['record_id'], unique=False)
    op.create_index(op.f('ix_update_logs_table_name'), 'update_logs', ['table_name'], unique=False)
    op.create_index('ix_update_logs_table_record', 'update_logs', ['table_name', 'record_id'], unique=False)
    op.create_index(op.f('ix_update_logs_update_at'), 'update_logs', ['update_at'], unique=False)
    op.create_index('ix_update_logs_update_at_type', 'update_logs', ['update_at', 'update_type'], unique=False)
    op.create_index(op.f('ix_update_logs_update_by'), 'update_logs', ['update_by'], unique=False)
    op.create_index(op.f('ix_update_logs_update_type'), 'update_logs', ['update_type'], unique=False)
    op.create_table('leagues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.Column('update_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leagues_external_id'), 'leagues', ['external_id'], unique=True)
    op.create_index(op.f('ix_leagues_name'), 'leagues', ['name'], unique=False)
    op.create_index('ix_leagues_name_country', 'leagues', ['name', 'country_id'], unique=False)
    op.create_table('odds_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('odds_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('key', sa.String(length=50), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.Column('update_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['odds_type_id'], ['odds_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_odds_values_name'), 'odds_values', ['name'], unique=False)
    op.create_index(op.f('ix_odds_values_odds_type_id'), 'odds_values', ['odds_type_id'], unique=False)
    op.create_index('ix_odds_values_type_key', 'odds_values', ['odds_type_id', 'key'], unique=True)
    op.create_index('ix_odds_values_type_order', 'odds_values', ['odds_type_id', 'display_order'], unique=False)
    op.create_table('venues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('surface', sa.String(length=50), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.Column('update_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venues_city'), 'venues', ['city'], unique=False)
    op.create_index('ix_venues_external_id', 'venues', ['external_id'], unique=False)
    op.create_index(op.f('ix_venues_name'), 'venues', ['name'], unique=False)
    op.create_index('ix_venues_name_city', 'venues', ['name', 'city'], unique=False)
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=True),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.Column('update_by', sa.String(length=50), nullable=True),
    sa.CheckConstraint('end_date >= start_date', name='end_date_after_start_date'),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seasons_external_id'), 'seasons', ['external_id'], unique=False)
    op.create_index(op.f('ix_seasons_is_current'), 'seasons', ['is_current'], unique=False)
    op.create_index('ix_seasons_league_year', 'seasons', ['league_id', 'year'], unique=False)
    op.create_index(op.f('ix_seasons_year'), 'seasons', ['year'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=5), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('founded', sa.SmallInteger(), nullable=True),
    sa.Column('is_national', sa.Boolean(), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('total_matches', sa.Integer(), nullable=True),
    sa.Column('total_wins', sa.Integer(), nullable=True),
    sa.Column('total_draws', sa.Integer(), nullable=True),
    sa.Column('total_losses', sa.Integer(), nullable=True),
    sa.Column('total_goals_scored', sa.Integer(), nullable=True),
    sa.Column('total_goals_conceded', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.Column('update_by', sa.String(length=50), nullable=True),
    sa.CheckConstraint('founded >= 1800 AND founded <= 2100', name='check_founded_range'),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_code'), 'teams', ['code'], unique=False)
    op.create_index('ix_teams_external_id', 'teams', ['external_id'], unique=False)
    op.create_index(op.f('ix_teams_name'), 'teams', ['name'], unique=False)
    op.create_index('ix_teams_name_country_id', 'teams', ['name', 'country_id'], unique=False)
    op.create_table('coaches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('firstname', sa.String(length=100), nullable=True),
    sa.Column('lastname', sa.String(length=100), nullable=True),
    sa.Column('nationality_id', sa.Integer(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('photo_url', sa.String(length=255), nullable=True),
    sa.Column('career_matches', sa.Integer(), nullable=True),
    sa.Column('career_wins', sa.Integer(), nullable=True),
    sa.Column('career_draws', sa.Integer(), nullable=True),
    sa.Column('career_losses', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.Column('update_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['nationality_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id')
    )
    op.create_index(op.f('ix_coaches_external_id'), 'coaches', ['external_id'], unique=True)
    op.create_index(op.f('ix_coaches_name'), 'coaches', ['name'], unique=False)
    op.create_index('ix_coaches_name_nationality', 'coaches', ['name', 'nationality_id'], unique=False)
    op.create_table('fixtures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=True),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('round', sa.String(length=100), nullable=True),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('referee', sa.String(length=100), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('elapsed_time', sa.SmallInteger(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('home_score', sa.SmallInteger(), nullable=True),
    sa.Column('away_score', sa.SmallInteger(), nullable=True),
    sa.Column('is_finished', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.Column('update_by', sa.String(length=50), nullable=True),
    sa.CheckConstraint('home_team_id != away_team_id', name='home_away_teams_different'),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['fixture_statuses.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fixtures_away_team_id'), 'fixtures', ['away_team_id'], unique=False)
    op.create_index(op.f('ix_fixtures_date'), 'fixtures', ['date'], unique=False)
    op.create_index('ix_fixtures_date_status', 'fixtures', ['date', 'status_id'], unique=False)
    op.create_index(op.f('ix_fixtures_external_id'), 'fixtures', ['external_id'], unique=True)
    op.create_index('ix_fixtures_home_away_season', 'fixtures', ['home_team_id', 'away_team_id', 'season_id'], unique=False)
    op.create_index(op.f('ix_fixtures_home_team_id'), 'fixtures', ['home_team_id'], unique=False)
    op.create_index(op.f('ix_fixtures_league_id'), 'fixtures', ['league_id'], unique=False)
    op.create_index('ix_fixtures_league_season_date', 'fixtures', ['league_id', 'season_id', 'date'], unique=False)
    op.create_index(op.f('ix_fixtures_season_id'), 'fixtures', ['season_id'], unique=False)
    op.create_index(op.f('ix_fixtures_status_id'), 'fixtures', ['status_id'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('firstname', sa.String(length=100), nullable=True),
    sa.Column('lastname', sa.String(length=100), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('nationality_id', sa.Integer(), nullable=True),
    sa.Column('height', sa.SmallInteger(), nullable=True),
    sa.Column('weight', sa.SmallInteger(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(length=2), nullable=False),
    sa.Column('number', sa.SmallInteger(), nullable=True),
    sa.Column('injured', sa.Boolean(), nullable=True),
    sa.Column('photo_url', sa.String(length=255), nullable=True),
    sa.Column('season_goals', sa.Integer(), nullable=True),
    sa.Column('season_assists', sa.Integer(), nullable=True),
    sa.Column('season_yellow_cards', sa.SmallInteger(), nullable=True),
    sa.Column('season_red_cards', sa.SmallInteger(), nullable=True),
    sa.Column('total_appearances', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.Column('update_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['nationality_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_external_id'), 'players', ['external_id'], unique=True)
    op.create_index('ix_players_injured', 'players', ['injured'], unique=False)
    op.create_index(op.f('ix_players_name'), 'players', ['name'], unique=False)
    op.create_index('ix_players_name_team', 'players', ['name', 'team_id'], unique=False)
    op.create_index('ix_players_position_team', 'players', ['position', 'team_id'], unique=False)
    op.create_index(op.f('ix_players_team_id'), 'players', ['team_id'], unique=False)
    op.create_table('standings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.SmallInteger(), nullable=False),
    sa.Column('points', sa.SmallInteger(), nullable=True),
    sa.Column('goals_diff', sa.SmallInteger(), nullable=True),
    sa.Column('form', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('played', sa.SmallInteger(), nullable=True),
    sa.Column('won', sa.SmallInteger(), nullable=True),
    sa.Column('drawn', sa.SmallInteger(), nullable=True),
    sa.Column('lost', sa.SmallInteger(), nullable=True),
    sa.Column('goals_for', sa.SmallInteger(), nullable=True),
    sa.Column('goals_against', sa.SmallInteger(), nullable=True),
    sa.Column('home_played', sa.SmallInteger(), nullable=True),
    sa.Column('home_won', sa.SmallInteger(), nullable=True),
    sa.Column('home_drawn', sa.SmallInteger(), nullable=True),
    sa.Column('home_lost', sa.SmallInteger(), nullable=True),
    sa.Column('home_goals_for', sa.SmallInteger(), nullable=True),
    sa.Column('home_goals_against', sa.SmallInteger(), nullable=True),
    sa.Column('away_played', sa.SmallInteger(), nullable=True),
    sa.Column('away_won', sa.SmallInteger(), nullable=True),
    sa.Column('away_drawn', sa.SmallInteger(), nullable=True),
    sa.Column('away_lost', sa.SmallInteger(), nullable=True),
    sa.Column('away_goals_for', sa.SmallInteger(), nullable=True),
    sa.Column('away_goals_against', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.Column('update_by', sa.String(length=50), nullable=True),
    sa.CheckConstraint('away_played = away_won + away_drawn + away_lost', name='away_matches_check'),
    sa.CheckConstraint('goals_against = home_goals_against + away_goals_against', name='total_vs_home_away_goals_against_check'),
    sa.CheckConstraint('goals_for = home_goals_for + away_goals_for', name='total_vs_home_away_goals_for_check'),
    sa.CheckConstraint('home_played = home_won + home_drawn + home_lost', name='home_matches_check'),
    sa.CheckConstraint('played = home_played + away_played', name='total_vs_home_away_matches_check'),
    sa.CheckConstraint('played = won + drawn + lost', name='total_matches_check'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_standings_season_id'), 'standings', ['season_id'], unique=False)
    op.create_index('ix_standings_season_points', 'standings', ['season_id', 'points'], unique=False)
    op.create_index('ix_standings_season_rank', 'standings', ['season_id', 'rank'], unique=False)
    op.create_index(op.f('ix_standings_team_id'), 'standings', ['team_id'], unique=False)
    op.create_index('ix_standings_update_at', 'standings', ['update_at'], unique=False)
    op.create_table('team_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('form', sa.String(length=100), nullable=True),
    sa.Column('matches_played_home', sa.SmallInteger(), nullable=True),
    sa.Column('matches_played_away', sa.SmallInteger(), nullable=True),
    sa.Column('matches_played_total', sa.SmallInteger(), nullable=True),
    sa.Column('wins_home', sa.SmallInteger(), nullable=True),
    sa.Column('wins_away', sa.SmallInteger(), nullable=True),
    sa.Column('wins_total', sa.SmallInteger(), nullable=True),
    sa.Column('draws_home', sa.SmallInteger(), nullable=True),
    sa.Column('draws_away', sa.SmallInteger(), nullable=True),
    sa.Column('draws_total', sa.SmallInteger(), nullable=True),
    sa.Column('losses_home', sa.SmallInteger(), nullable=True),
    sa.Column('losses_away', sa.SmallInteger(), nullable=True),
    sa.Column('losses_total', sa.SmallInteger(), nullable=True),
    sa.Column('goals_for_home', sa.SmallInteger(), nullable=True),
    sa.Column('goals_for_away', sa.SmallInteger(), nullable=True),
    sa.Column('goals_for_total', sa.SmallInteger(), nullable=True),
    sa.Column('goals_against_home', sa.SmallInteger(), nullable=True),
    sa.Column('goals_against_away', sa.SmallInteger(), nullable=True),
    sa.Column('goals_against_total', sa.SmallInteger(), nullable=True),
    sa.Column('goals_for_average_home', sa.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('goals_for_average_away', sa.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('goals_for_average_total', sa.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('goals_against_average_home', sa.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('goals_against_average_away', sa.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('goals_against_average_total', sa.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('streak_wins', sa.SmallInteger(), nullable=True),
    sa.Column('streak_draws', sa.SmallInteger(), nullable=True),
    sa.Column('streak_losses', sa.SmallInteger(), nullable=True),
    sa.Column('biggest_win_home', sa.String(length=10), nullable=True),
    sa.Column('biggest_win_away', sa.String(length=10), nullable=True),
    sa.Column('biggest_loss_home', sa.String(length=10), nullable=True),
    sa.Column('biggest_loss_away', sa.String(length=10), nullable=True),
    sa.Column('clean_sheets_home', sa.SmallInteger(), nullable=True),
    sa.Column('clean_sheets_away', sa.SmallInteger(), nullable=True),
    sa.Column('clean_sheets_total', sa.SmallInteger(), nullable=True),
    sa.Column('failed_to_score_home', sa.SmallInteger(), nullable=True),
    sa.Column('failed_to_score_away', sa.SmallInteger(), nullable=True),
    sa.Column('failed_to_score_total', sa.SmallInteger(), nullable=True),
    sa.Column('penalties_scored', sa.SmallInteger(), nullable=True),
    sa.Column('penalties_missed', sa.SmallInteger(), nullable=True),
    sa.Column('penalties_total', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.Column('update_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_statistics_league_id'), 'team_statistics', ['league_id'], unique=False)
    op.create_index(op.f('ix_team_statistics_season_id'), 'team_statistics', ['season_id'], unique=False)
    op.create_index(op.f('ix_team_statistics_team_id'), 'team_statistics', ['team_id'], unique=False)
    op.create_index('ix_team_stats_league_season', 'team_statistics', ['league_id', 'season_id'], unique=False)
    op.create_index('ix_team_stats_team_season', 'team_statistics', ['team_id', 'season_id'], unique=False)
    op.create_table('coach_careers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('matches', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('draws', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.Column('update_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coach_careers_coach_id'), 'coach_careers', ['coach_id'], unique=False)
    op.create_index('ix_coach_careers_coach_team', 'coach_careers', ['coach_id', 'team_id'], unique=False)
    op.create_index(op.f('ix_coach_careers_start_date'), 'coach_careers', ['start_date'], unique=False)
    op.create_index('ix_coach_careers_start_end_date', 'coach_careers', ['start_date', 'end_date'], unique=False)
    op.create_index(op.f('ix_coach_careers_team_id'), 'coach_careers', ['team_id'], unique=False)
    op.create_table('fixture_coaches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.Column('update_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], ),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fixture_coaches_coach_id'), 'fixture_coaches', ['coach_id'], unique=False)
    op.create_index(op.f('ix_fixture_coaches_fixture_id'), 'fixture_coaches', ['fixture_id'], unique=False)
    op.create_index('ix_fixture_coaches_fixture_team', 'fixture_coaches', ['fixture_id', 'team_id'], unique=False)
    op.create_index(op.f('ix_fixture_coaches_team_id'), 'fixture_coaches', ['team_id'], unique=False)
    op.create_table('fixture_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('time_elapsed', sa.SmallInteger(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=True),
    sa.Column('detail', sa.String(length=100), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('assist_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.Column('update_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['assist_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fixture_events_assist_id'), 'fixture_events', ['assist_id'], unique=False)
    op.create_index(op.f('ix_fixture_events_event_type'), 'fixture_events', ['event_type'], unique=False)
    op.create_index('ix_fixture_events_event_type_team', 'fixture_events', ['event_type', 'team_id'], unique=False)
    op.create_index(op.f('ix_fixture_events_fixture_id'), 'fixture_events', ['fixture_id'], unique=False)
    op.create_index('ix_fixture_events_fixture_time', 'fixture_events', ['fixture_id', 'time_elapsed'], unique=False)
    op.create_index(op.f('ix_fixture_events_player_id'), 'fixture_events', ['player_id'], unique=False)
    op.create_index(op.f('ix_fixture_events_team_id'), 'fixture_events', ['team_id'], unique=False)
    op.create_table('fixture_h2h',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_fixture_id', sa.Integer(), nullable=False),
    sa.Column('related_fixture_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.Column('update_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['reference_fixture_id'], ['fixtures.id'], ),
    sa.ForeignKeyConstraint(['related_fixture_id'], ['fixtures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fixture_h2h_reference_fixture_id'), 'fixture_h2h', ['reference_fixture_id'], unique=False)
    op.create_index('ix_fixture_h2h_reference_related', 'fixture_h2h', ['reference_fixture_id', 'related_fixture_id'], unique=True)
    op.create_index(op.f('ix_fixture_h2h_related_fixture_id'), 'fixture_h2h', ['related_fixture_id'], unique=False)
    op.create_table('fixture_lineups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('formation', sa.String(length=10), nullable=True),
    sa.Column('player_primary_color', sa.String(length=6), nullable=True),
    sa.Column('player_number_color', sa.String(length=6), nullable=True),
    sa.Column('player_border_color', sa.String(length=6), nullable=True),
    sa.Column('goalkeeper_primary_color', sa.String(length=6), nullable=True),
    sa.Column('goalkeeper_number_color', sa.String(length=6), nullable=True),
    sa.Column('goalkeeper_border_color', sa.String(length=6), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.Column('update_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fixture_lineups_fixture_id'), 'fixture_lineups', ['fixture_id'], unique=False)
    op.create_index('ix_fixture_lineups_fixture_team', 'fixture_lineups', ['fixture_id', 'team_id'], unique=False)
    op.create_index(op.f('ix_fixture_lineups_team_id'), 'fixture_lineups', ['team_id'], unique=False)
    op.create_table('fixture_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('halftime', sa.SmallInteger(), nullable=True),
    sa.Column('fulltime', sa.SmallInteger(), nullable=True),
    sa.Column('extratime', sa.SmallInteger(), nullable=True),
    sa.Column('penalty', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.Column('update_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fixture_scores_fixture_id'), 'fixture_scores', ['fixture_id'], unique=False)
    op.create_index('ix_fixture_scores_fixture_team', 'fixture_scores', ['fixture_id', 'team_id'], unique=False)
    op.create_index(op.f('ix_fixture_scores_team_id'), 'fixture_scores', ['team_id'], unique=False)
    op.create_table('fixture_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('stat_type', sa.String(length=50), nullable=True),
    sa.Column('value', sa.DECIMAL(precision=7, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.Column('update_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fixture_statistics_fixture_id'), 'fixture_statistics', ['fixture_id'], unique=False)
    op.create_index('ix_fixture_statistics_fixture_team_type', 'fixture_statistics', ['fixture_id', 'team_id', 'stat_type'], unique=False)
    op.create_index(op.f('ix_fixture_statistics_stat_type'), 'fixture_statistics', ['stat_type'], unique=False)
    op.create_index(op.f('ix_fixture_statistics_team_id'), 'fixture_statistics', ['team_id'], unique=False)
    op.create_table('odds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('bookmaker_id', sa.Integer(), nullable=False),
    sa.Column('odds_type_id', sa.Integer(), nullable=False),
    sa.Column('odds_value_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.DECIMAL(precision=7, scale=2), nullable=False),
    sa.Column('is_main', sa.Boolean(), nullable=True),
    sa.Column('probability', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.Column('update_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['bookmaker_id'], ['bookmakers.id'], ),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.ForeignKeyConstraint(['odds_type_id'], ['odds_types.id'], ),
    sa.ForeignKeyConstraint(['odds_value_id'], ['odds_values.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_odds_bookmaker_id'), 'odds', ['bookmaker_id'], unique=False)
    op.create_index('ix_odds_fixture_bookmaker_type', 'odds', ['fixture_id', 'bookmaker_id', 'odds_type_id'], unique=False)
    op.create_index(op.f('ix_odds_fixture_id'), 'odds', ['fixture_id'], unique=False)
    op.create_index('ix_odds_fixture_status', 'odds', ['fixture_id', 'status'], unique=False)
    op.create_index(op.f('ix_odds_last_update'), 'odds', ['last_update'], unique=False)
    op.create_index(op.f('ix_odds_odds_type_id'), 'odds', ['odds_type_id'], unique=False)
    op.create_index(op.f('ix_odds_odds_value_id'), 'odds', ['odds_value_id'], unique=False)
    op.create_index(op.f('ix_odds_status'), 'odds', ['status'], unique=False)
    op.create_table('player_injuries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('expected_return_date', sa.Date(), nullable=True),
    sa.Column('recovery_time', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.Column('update_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_injuries_fixture_id'), 'player_injuries', ['fixture_id'], unique=False)
    op.create_index(op.f('ix_player_injuries_player_id'), 'player_injuries', ['player_id'], unique=False)
    op.create_index('ix_player_injuries_player_start_date', 'player_injuries', ['player_id', 'start_date'], unique=False)
    op.create_index(op.f('ix_player_injuries_start_date'), 'player_injuries', ['start_date'], unique=False)
    op.create_index('ix_player_injuries_status_end_date', 'player_injuries', ['status', 'end_date'], unique=False)
    op.create_table('player_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('minutes_played', sa.SmallInteger(), nullable=True),
    sa.Column('position', sa.String(length=2), nullable=True),
    sa.Column('number', sa.SmallInteger(), nullable=True),
    sa.Column('rating', sa.DECIMAL(precision=3, scale=1), nullable=True),
    sa.Column('is_captain', sa.Boolean(), nullable=True),
    sa.Column('is_substitute', sa.Boolean(), nullable=True),
    sa.Column('shots_total', sa.SmallInteger(), nullable=True),
    sa.Column('shots_on_target', sa.SmallInteger(), nullable=True),
    sa.Column('goals', sa.SmallInteger(), nullable=True),
    sa.Column('assists', sa.SmallInteger(), nullable=True),
    sa.Column('passes', sa.SmallInteger(), nullable=True),
    sa.Column('key_passes', sa.SmallInteger(), nullable=True),
    sa.Column('pass_accuracy', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('tackles', sa.SmallInteger(), nullable=True),
    sa.Column('interceptions', sa.SmallInteger(), nullable=True),
    sa.Column('duels_total', sa.SmallInteger(), nullable=True),
    sa.Column('duels_won', sa.SmallInteger(), nullable=True),
    sa.Column('dribbles_success', sa.SmallInteger(), nullable=True),
    sa.Column('fouls_committed', sa.SmallInteger(), nullable=True),
    sa.Column('fouls_drawn', sa.SmallInteger(), nullable=True),
    sa.Column('yellow_cards', sa.SmallInteger(), nullable=True),
    sa.Column('red_cards', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.Column('update_by', sa.String(length=50), nullable=True),
    sa.CheckConstraint('duels_won <= duels_total', name='duels_won_lte_total'),
    sa.CheckConstraint('shots_on_target <= shots_total', name='shots_on_target_lte_total'),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_player_statistics_assists', 'player_statistics', ['assists'], unique=False)
    op.create_index(op.f('ix_player_statistics_fixture_id'), 'player_statistics', ['fixture_id'], unique=False)
    op.create_index('ix_player_statistics_goals', 'player_statistics', ['goals'], unique=False)
    op.create_index('ix_player_statistics_player_fixture', 'player_statistics', ['player_id', 'fixture_id'], unique=False)
    op.create_index(op.f('ix_player_statistics_player_id'), 'player_statistics', ['player_id'], unique=False)
    op.create_index('ix_player_statistics_rating', 'player_statistics', ['rating'], unique=False)
    op.create_index(op.f('ix_player_statistics_team_id'), 'player_statistics', ['team_id'], unique=False)
    op.create_table('player_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.Column('update_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_teams_player_id'), 'player_teams', ['player_id'], unique=False)
    op.create_index('ix_player_teams_player_season', 'player_teams', ['player_id', 'season_id'], unique=False)
    op.create_index('ix_player_teams_player_team', 'player_teams', ['player_id', 'team_id'], unique=False)
    op.create_index(op.f('ix_player_teams_season_id'), 'player_teams', ['season_id'], unique=False)
    op.create_index(op.f('ix_player_teams_team_id'), 'player_teams', ['team_id'], unique=False)
    op.create_index('ix_player_teams_team_season', 'player_teams', ['team_id', 'season_id'], unique=False)
    op.create_table('player_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('team_in_id', sa.Integer(), nullable=False),
    sa.Column('team_out_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.Column('update_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_in_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['team_out_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_transfers_date'), 'player_transfers', ['date'], unique=False)
    op.create_index('ix_player_transfers_player_date', 'player_transfers', ['player_id', 'date'], unique=False)
    op.create_index(op.f('ix_player_transfers_player_id'), 'player_transfers', ['player_id'], unique=False)
    op.create_index('ix_player_transfers_team_in_date', 'player_transfers', ['team_in_id', 'date'], unique=False)
    op.create_index(op.f('ix_player_transfers_team_in_id'), 'player_transfers', ['team_in_id'], unique=False)
    op.create_index('ix_player_transfers_team_out_date', 'player_transfers', ['team_out_id', 'date'], unique=False)
    op.create_index(op.f('ix_player_transfers_team_out_id'), 'player_transfers', ['team_out_id'], unique=False)
    op.create_index('ix_player_transfers_type', 'player_transfers', ['type'], unique=False)
    op.create_table('team_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(length=20), nullable=True),
    sa.Column('number', sa.SmallInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.Column('update_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_players_player_id'), 'team_players', ['player_id'], unique=False)
    op.create_index('ix_team_players_player_is_active', 'team_players', ['player_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_team_players_position'), 'team_players', ['position'], unique=False)
    op.create_index(op.f('ix_team_players_team_id'), 'team_players', ['team_id'], unique=False)
    op.create_index('ix_team_players_team_is_active', 'team_players', ['team_id', 'is_active'], unique=False)
    op.create_index('ix_team_players_team_position', 'team_players', ['team_id', 'position'], unique=False)
    op.create_table('fixture_lineup_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lineup_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.SmallInteger(), nullable=False),
    sa.Column('position', sa.String(length=2), nullable=False),
    sa.Column('grid', sa.String(length=5), nullable=True),
    sa.Column('is_substitute', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.Column('update_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['lineup_id'], ['fixture_lineups.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fixture_lineup_players_is_substitute'), 'fixture_lineup_players', ['is_substitute'], unique=False)
    op.create_index(op.f('ix_fixture_lineup_players_lineup_id'), 'fixture_lineup_players', ['lineup_id'], unique=False)
    op.create_index('ix_fixture_lineup_players_lineup_position', 'fixture_lineup_players', ['lineup_id', 'position'], unique=False)
    op.create_index(op.f('ix_fixture_lineup_players_player_id'), 'fixture_lineup_players', ['player_id'], unique=False)
    op.create_table('odds_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('odds_id', sa.Integer(), nullable=False),
    sa.Column('old_value', sa.DECIMAL(precision=7, scale=2), nullable=False),
    sa.Column('new_value', sa.DECIMAL(precision=7, scale=2), nullable=False),
    sa.Column('change_time', sa.DateTime(), nullable=False),
    sa.Column('movement', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.Column('update_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['odds_id'], ['odds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_odds_history_change_time'), 'odds_history', ['change_time'], unique=False)
    op.create_index('ix_odds_history_odds_change_time', 'odds_history', ['odds_id', 'change_time'], unique=False)
    op.create_index(op.f('ix_odds_history_odds_id'), 'odds_history', ['odds_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_odds_history_odds_id'), table_name='odds_history')
    op.drop_index('ix_odds_history_odds_change_time', table_name='odds_history')
    op.drop_index(op.f('ix_odds_history_change_time'), table_name='odds_history')
    op.drop_table('odds_history')
    op.drop_index(op.f('ix_fixture_lineup_players_player_id'), table_name='fixture_lineup_players')
    op.drop_index('ix_fixture_lineup_players_lineup_position', table_name='fixture_lineup_players')
    op.drop_index(op.f('ix_fixture_lineup_players_lineup_id'), table_name='fixture_lineup_players')
    op.drop_index(op.f('ix_fixture_lineup_players_is_substitute'), table_name='fixture_lineup_players')
    op.drop_table('fixture_lineup_players')
    op.drop_index('ix_team_players_team_position', table_name='team_players')
    op.drop_index('ix_team_players_team_is_active', table_name='team_players')
    op.drop_index(op.f('ix_team_players_team_id'), table_name='team_players')
    op.drop_index(op.f('ix_team_players_position'), table_name='team_players')
    op.drop_index('ix_team_players_player_is_active', table_name='team_players')
    op.drop_index(op.f('ix_team_players_player_id'), table_name='team_players')
    op.drop_table('team_players')
    op.drop_index('ix_player_transfers_type', table_name='player_transfers')
    op.drop_index(op.f('ix_player_transfers_team_out_id'), table_name='player_transfers')
    op.drop_index('ix_player_transfers_team_out_date', table_name='player_transfers')
    op.drop_index(op.f('ix_player_transfers_team_in_id'), table_name='player_transfers')
    op.drop_index('ix_player_transfers_team_in_date', table_name='player_transfers')
    op.drop_index(op.f('ix_player_transfers_player_id'), table_name='player_transfers')
    op.drop_index('ix_player_transfers_player_date', table_name='player_transfers')
    op.drop_index(op.f('ix_player_transfers_date'), table_name='player_transfers')
    op.drop_table('player_transfers')
    op.drop_index('ix_player_teams_team_season', table_name='player_teams')
    op.drop_index(op.f('ix_player_teams_team_id'), table_name='player_teams')
    op.drop_index(op.f('ix_player_teams_season_id'), table_name='player_teams')
    op.drop_index('ix_player_teams_player_team', table_name='player_teams')
    op.drop_index('ix_player_teams_player_season', table_name='player_teams')
    op.drop_index(op.f('ix_player_teams_player_id'), table_name='player_teams')
    op.drop_table('player_teams')
    op.drop_index(op.f('ix_player_statistics_team_id'), table_name='player_statistics')
    op.drop_index('ix_player_statistics_rating', table_name='player_statistics')
    op.drop_index(op.f('ix_player_statistics_player_id'), table_name='player_statistics')
    op.drop_index('ix_player_statistics_player_fixture', table_name='player_statistics')
    op.drop_index('ix_player_statistics_goals', table_name='player_statistics')
    op.drop_index(op.f('ix_player_statistics_fixture_id'), table_name='player_statistics')
    op.drop_index('ix_player_statistics_assists', table_name='player_statistics')
    op.drop_table('player_statistics')
    op.drop_index('ix_player_injuries_status_end_date', table_name='player_injuries')
    op.drop_index(op.f('ix_player_injuries_start_date'), table_name='player_injuries')
    op.drop_index('ix_player_injuries_player_start_date', table_name='player_injuries')
    op.drop_index(op.f('ix_player_injuries_player_id'), table_name='player_injuries')
    op.drop_index(op.f('ix_player_injuries_fixture_id'), table_name='player_injuries')
    op.drop_table('player_injuries')
    op.drop_index(op.f('ix_odds_status'), table_name='odds')
    op.drop_index(op.f('ix_odds_odds_value_id'), table_name='odds')
    op.drop_index(op.f('ix_odds_odds_type_id'), table_name='odds')
    op.drop_index(op.f('ix_odds_last_update'), table_name='odds')
    op.drop_index('ix_odds_fixture_status', table_name='odds')
    op.drop_index(op.f('ix_odds_fixture_id'), table_name='odds')
    op.drop_index('ix_odds_fixture_bookmaker_type', table_name='odds')
    op.drop_index(op.f('ix_odds_bookmaker_id'), table_name='odds')
    op.drop_table('odds')
    op.drop_index(op.f('ix_fixture_statistics_team_id'), table_name='fixture_statistics')
    op.drop_index(op.f('ix_fixture_statistics_stat_type'), table_name='fixture_statistics')
    op.drop_index('ix_fixture_statistics_fixture_team_type', table_name='fixture_statistics')
    op.drop_index(op.f('ix_fixture_statistics_fixture_id'), table_name='fixture_statistics')
    op.drop_table('fixture_statistics')
    op.drop_index(op.f('ix_fixture_scores_team_id'), table_name='fixture_scores')
    op.drop_index('ix_fixture_scores_fixture_team', table_name='fixture_scores')
    op.drop_index(op.f('ix_fixture_scores_fixture_id'), table_name='fixture_scores')
    op.drop_table('fixture_scores')
    op.drop_index(op.f('ix_fixture_lineups_team_id'), table_name='fixture_lineups')
    op.drop_index('ix_fixture_lineups_fixture_team', table_name='fixture_lineups')
    op.drop_index(op.f('ix_fixture_lineups_fixture_id'), table_name='fixture_lineups')
    op.drop_table('fixture_lineups')
    op.drop_index(op.f('ix_fixture_h2h_related_fixture_id'), table_name='fixture_h2h')
    op.drop_index('ix_fixture_h2h_reference_related', table_name='fixture_h2h')
    op.drop_index(op.f('ix_fixture_h2h_reference_fixture_id'), table_name='fixture_h2h')
    op.drop_table('fixture_h2h')
    op.drop_index(op.f('ix_fixture_events_team_id'), table_name='fixture_events')
    op.drop_index(op.f('ix_fixture_events_player_id'), table_name='fixture_events')
    op.drop_index('ix_fixture_events_fixture_time', table_name='fixture_events')
    op.drop_index(op.f('ix_fixture_events_fixture_id'), table_name='fixture_events')
    op.drop_index('ix_fixture_events_event_type_team', table_name='fixture_events')
    op.drop_index(op.f('ix_fixture_events_event_type'), table_name='fixture_events')
    op.drop_index(op.f('ix_fixture_events_assist_id'), table_name='fixture_events')
    op.drop_table('fixture_events')
    op.drop_index(op.f('ix_fixture_coaches_team_id'), table_name='fixture_coaches')
    op.drop_index('ix_fixture_coaches_fixture_team', table_name='fixture_coaches')
    op.drop_index(op.f('ix_fixture_coaches_fixture_id'), table_name='fixture_coaches')
    op.drop_index(op.f('ix_fixture_coaches_coach_id'), table_name='fixture_coaches')
    op.drop_table('fixture_coaches')
    op.drop_index(op.f('ix_coach_careers_team_id'), table_name='coach_careers')
    op.drop_index('ix_coach_careers_start_end_date', table_name='coach_careers')
    op.drop_index(op.f('ix_coach_careers_start_date'), table_name='coach_careers')
    op.drop_index('ix_coach_careers_coach_team', table_name='coach_careers')
    op.drop_index(op.f('ix_coach_careers_coach_id'), table_name='coach_careers')
    op.drop_table('coach_careers')
    op.drop_index('ix_team_stats_team_season', table_name='team_statistics')
    op.drop_index('ix_team_stats_league_season', table_name='team_statistics')
    op.drop_index(op.f('ix_team_statistics_team_id'), table_name='team_statistics')
    op.drop_index(op.f('ix_team_statistics_season_id'), table_name='team_statistics')
    op.drop_index(op.f('ix_team_statistics_league_id'), table_name='team_statistics')
    op.drop_table('team_statistics')
    op.drop_index('ix_standings_update_at', table_name='standings')
    op.drop_index(op.f('ix_standings_team_id'), table_name='standings')
    op.drop_index('ix_standings_season_rank', table_name='standings')
    op.drop_index('ix_standings_season_points', table_name='standings')
    op.drop_index(op.f('ix_standings_season_id'), table_name='standings')
    op.drop_table('standings')
    op.drop_index(op.f('ix_players_team_id'), table_name='players')
    op.drop_index('ix_players_position_team', table_name='players')
    op.drop_index('ix_players_name_team', table_name='players')
    op.drop_index(op.f('ix_players_name'), table_name='players')
    op.drop_index('ix_players_injured', table_name='players')
    op.drop_index(op.f('ix_players_external_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_fixtures_status_id'), table_name='fixtures')
    op.drop_index(op.f('ix_fixtures_season_id'), table_name='fixtures')
    op.drop_index('ix_fixtures_league_season_date', table_name='fixtures')
    op.drop_index(op.f('ix_fixtures_league_id'), table_name='fixtures')
    op.drop_index(op.f('ix_fixtures_home_team_id'), table_name='fixtures')
    op.drop_index('ix_fixtures_home_away_season', table_name='fixtures')
    op.drop_index(op.f('ix_fixtures_external_id'), table_name='fixtures')
    op.drop_index('ix_fixtures_date_status', table_name='fixtures')
    op.drop_index(op.f('ix_fixtures_date'), table_name='fixtures')
    op.drop_index(op.f('ix_fixtures_away_team_id'), table_name='fixtures')
    op.drop_table('fixtures')
    op.drop_index('ix_coaches_name_nationality', table_name='coaches')
    op.drop_index(op.f('ix_coaches_name'), table_name='coaches')
    op.drop_index(op.f('ix_coaches_external_id'), table_name='coaches')
    op.drop_table('coaches')
    op.drop_index('ix_teams_name_country_id', table_name='teams')
    op.drop_index(op.f('ix_teams_name'), table_name='teams')
    op.drop_index('ix_teams_external_id', table_name='teams')
    op.drop_index(op.f('ix_teams_code'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_seasons_year'), table_name='seasons')
    op.drop_index('ix_seasons_league_year', table_name='seasons')
    op.drop_index(op.f('ix_seasons_is_current'), table_name='seasons')
    op.drop_index(op.f('ix_seasons_external_id'), table_name='seasons')
    op.drop_table('seasons')
    op.drop_index('ix_venues_name_city', table_name='venues')
    op.drop_index(op.f('ix_venues_name'), table_name='venues')
    op.drop_index('ix_venues_external_id', table_name='venues')
    op.drop_index(op.f('ix_venues_city'), table_name='venues')
    op.drop_table('venues')
    op.drop_index('ix_odds_values_type_order', table_name='odds_values')
    op.drop_index('ix_odds_values_type_key', table_name='odds_values')
    op.drop_index(op.f('ix_odds_values_odds_type_id'), table_name='odds_values')
    op.drop_index(op.f('ix_odds_values_name'), table_name='odds_values')
    op.drop_table('odds_values')
    op.drop_index('ix_leagues_name_country', table_name='leagues')
    op.drop_index(op.f('ix_leagues_name'), table_name='leagues')
    op.drop_index(op.f('ix_leagues_external_id'), table_name='leagues')
    op.drop_table('leagues')
    op.drop_index(op.f('ix_update_logs_update_type'), table_name='update_logs')
    op.drop_index(op.f('ix_update_logs_update_by'), table_name='update_logs')
    op.drop_index('ix_update_logs_update_at_type', table_name='update_logs')
    op.drop_index(op.f('ix_update_logs_update_at'), table_name='update_logs')
    op.drop_index('ix_update_logs_table_record', table_name='update_logs')
    op.drop_index(op.f('ix_update_logs_table_name'), table_name='update_logs')
    op.drop_index(op.f('ix_update_logs_record_id'), table_name='update_logs')
    op.drop_table('update_logs')
    op.drop_index(op.f('ix_performance_logs_trace_id'), table_name='performance_logs')
    op.drop_index('ix_performance_logs_timestamp_status', table_name='performance_logs')
    op.drop_index(op.f('ix_performance_logs_timestamp'), table_name='performance_logs')
    op.drop_index(op.f('ix_performance_logs_status'), table_name='performance_logs')
    op.drop_index(op.f('ix_performance_logs_operation'), table_name='performance_logs')
    op.drop_index('ix_performance_logs_component_operation', table_name='performance_logs')
    op.drop_index(op.f('ix_performance_logs_component'), table_name='performance_logs')
    op.drop_table('performance_logs')
    op.drop_index(op.f('ix_odds_types_key'), table_name='odds_types')
    op.drop_index(op.f('ix_odds_types_external_id'), table_name='odds_types')
    op.drop_index('ix_odds_types_category_order', table_name='odds_types')
    op.drop_index(op.f('ix_odds_types_category'), table_name='odds_types')
    op.drop_table('odds_types')
    op.drop_index(op.f('ix_media_assets_type'), table_name='media_assets')
    op.drop_table('media_assets')
    op.drop_index(op.f('ix_fixture_statuses_status_type'), table_name='fixture_statuses')
    op.drop_index('ix_fixture_statuses_short_code_type', table_name='fixture_statuses')
    op.drop_table('fixture_statuses')
    op.drop_index(op.f('ix_countries_name'), table_name='countries')
    op.drop_index(op.f('ix_countries_external_id'), table_name='countries')
    op.drop_index(op.f('ix_countries_code'), table_name='countries')
    op.drop_table('countries')
    op.drop_index(op.f('ix_bookmakers_name'), table_name='bookmakers')
    op.drop_index('ix_bookmakers_is_active_priority', table_name='bookmakers')
    op.drop_index(op.f('ix_bookmakers_external_id'), table_name='bookmakers')
    op.drop_table('bookmakers')
    op.drop_index('ix_app_metrics_timestamp_type', table_name='app_metrics')
    op.drop_index(op.f('ix_app_metrics_timestamp'), table_name='app_metrics')
    op.drop_index(op.f('ix_app_metrics_metric_type'), table_name='app_metrics')
    op.drop_table('app_metrics')
    # ### end Alembic commands ###
